[tool.poetry]
name = "myoboku"
version = "0.1.0"
description = ""
authors = ["PN-picsell <pierre-nicolas@picsellia.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
orjson = "^3.11.1"
docker = "^7.1.0"
picsellia = "^6.24.0"
httpx = "^0.28.1"
requests = "^2.32.5"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
src = ["app"]

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I", # isort
    "C", # flake8-comprehensions
    "B", # flake8-bugbear
    "UP", # pyupgrade
]
ignore = [
    "B904", # raise from - do not fix until we know how to handle exceptions
    "E501", # line too long - 490 errors
]
